### PR TITLE
docs: adapt issues to new issue form

### LINKED ISSUE #176: [Feature] Upgrade Issue Templates to use GitHub Issue Forms
### 🚀 Feature Proposal

GitHub has recently rolled out a [public beta for their issue forms](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) feature. This would allow you to create interactive issue templates and validate them 🤯.

### Motivation

This repository currently uses the older issue template format. Your task is to create GitHub issue forms for this repository. We can use this repo's issue templates as a reference for this PR.

### PR DESCRIPTION
**Pull request by schmelto**
resolve #176

### CODE REVIEW

**Review by westeezy — APPROVED** [review]
Thanks for looking into this. I think this is a good start on the template and we can expand it overtime if needed

**Comment by Hard-Coder05** [comment]
@westeezy I had asked for the issue first! How can his PR be accepted?

**Comment by Hard-Coder05** [comment]
> @Hard-Coder05 given i know see we have two PRs tackling the same issue let me take a moment today to review and accept one. I'll post an update once I have time to read through the original issue and both PRs

Yeah sure! Do review them and let me know what do you think!

**Comment by westeezy** [comment]
Closing in favor of #181

**Pull request closed without merging**
